[project]
name = "faster-whisper-rocm"
version = "0.1.0"
description = "A ROCm based faster-whisper implemenation for AMD GPU support"
readme = "README.md"
authors = [
  { name = "elvee", email = "lowie@beecave.nl" },
]
requires-python = ">=3.9"
license = { text = "MIT" }
keywords = ["cli", "typer", "faster-whisper", "amd", "gpu", "rocm"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

# Keep package at repo root under `my_package/`
[tool.pdm]

[project.urls]
Repository = "https://github.com/beecave-homelab/faster-whisper-rocm.git"

[project.dependencies]
typer = ">=0.12,<1.0"
rich = ">=13,<14"

[project.optional-dependencies]
dev = [
  "pytest>=8",
  "pytest-cov>=5",
  "ruff>=0.5",
  "black>=24",
  "mypy>=1.10",
]

[project.scripts]
my-package = "my_package.cli.app:app"

[tool.ruff]
line-length = 88

[tool.black]
line-length = 88

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]
